config/routes.rb
Soothsayer::Application.routes.draw do
  resources :venues
  resources :bands
  resources :gigs
  resources :songs

root to: 'welcome#index'

  

end

app/models/band.rb
class Band < ActiveRecord::Base
	has_many :songs
	has_and_belongs_to_many :gigs
	has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
end

app/models/gig.rb
class Gig < ActiveRecord::Base
	has_and_belongs_to_many :bands
	belongs_to :venue
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_attached_file :mp3,
                    :url => '/system/:class/:id_partition/:basename.:extension',
                    :path => ':rails_root/public/system/:class/:id_partition/:basename.:extension'

  validates_attachment_presence :mp3
  validates_attachment_content_type :mp3, :content_type => [ 'application/mp3', 'application/x-mp3', 'audio/mpeg', 'audio/mp3' ]
  validates_attachment_size :mp3, :less_than => 20.megabytes
	belongs_to :band
end

app/models/venue.rb
class Venue < ActiveRecord::Base
	has_many :gigs
	validates :title, presence: true, length: {minimum: 5 }
	has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

	def destroy
		@band = Band.find(params[:id])
		@band.destroy
		
		redirect_to bands_path
	end

	def update
		@band = Band.find(params[:id])
		
		if @band.update(params[:band].permit(:title, :description, :genre, :photo))
			redirect_to @band
		else
			render 'edit'
		end
	end
	def index
		@bands = Band.all
	end

  def new
		@band = Band.new
	end

	def edit
		@band = Band.find(params[:id])
	end

  def create
		@band = Band.new(params[:band].permit(:title, :description, :genre, :photo))
		if @band.save
			redirect_to @band
		else
			render 'new'
		end
	end

	def show
		@band = Band.find(params[:id])
	end
	private
		def post_params
			params.require(:band).permit(:title, :description, :genre, :photo)
		end  
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController

	def destroy
		@gig = Gig.find(params[:id])
		@gig.destroy
		
		redirect_to gigs_path
	end

	def update
		@gig = Gig.find(params[:id])
		
		if @gig.update(params[:gig].permit(:title, :description, :start_time, :venue_id, :band_ids => []))
			redirect_to @gig
		else
			render 'edit'
		end
	end
	def index
		@gigs = Gig.all
	end

  def new
		@gig = Gig.new
	end

	def edit
		@gig = Gig.find(params[:id])
	end

  def create
		@gig = Gig.new(params[:gig].permit(:title, :description, :start_time, :venue_id, :band_ids => []))
		if @gig.save
			redirect_to @gig
		else
			render 'new'
		end
	end

	def show
#		@gig = Gig.find(params[:id])
		@gig = Gig.find(params[:id])
	end
	private
		def post_params
			params.require(:gig).permit(:title, :description, :start_time, :venue_id, :band_ids)
		end  
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

	def destroy
		@song = Song.find(params[:id])
		@song.destroy
		
		redirect_to songs_path
	end

	def update
		@song = Song.find(params[:id])
		
		if @song.update(params[:song].permit(:title, :band_title, :genre, :mp3, :band_id))
			redirect_to @song
		else
			render 'edit'
		end
	end
	def index
		@songs = Song.all
	end

  def new
		@song = Song.new
	end

	def edit
		@song = Song.find(params[:id])
	end

  def create
		@song = Song.new(params[:song].permit(:title, :band_title, :genre, :mp3, :band_id))
		if @song.save
			redirect_to @song
		else
			render 'new'
		end
	end

	def show
		@song = Song.find(params[:id])
	end
	private
		def post_params
			params.require(:song).permit(:title, :band_title, :genre, :mp3, :band_id)
		end  
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

	def destroy
		@venue = Venue.find(params[:id])
		@venue.destroy
		
		redirect_to venues_path
	end

	def update
		@venue = Venue.find(params[:id])
		
		if @venue.update(params[:venue].permit(:title, :text, :photo))
			redirect_to @venue
		else
			render 'edit'
		end
	end
	def index
		@venues = Venue.all
	end

  def new
		@venue = Venue.new
	end

	def edit
		@venue = Venue.find(params[:id])
	end

  def create
		@venue = Venue.new(params[:venue].permit(:title, :text))
		if @venue.save
			redirect_to @venue
		else
			render 'new'
		end
	end

	def show
		@venue = Venue.find(params[:id])
	end
	private
		def venue_params
			params.require(:venue).permit(:title, :text, :photo)
		end  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bands/_form.html.erb
<%= form_for @band, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :genre, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :genre, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :photo, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :photo, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                bands_path, :class => 'btn' %>
  </div>
<% end %>

app/views/bands/edit.html.erb
<%- model_class = Band -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bands/index.html.erb
<%- model_class = Band -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
			<th><%= link_to t('.new', :default => t("helpers.links.new")),
            new_band_path,
            :class => 'btn btn-primary' %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:genre) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bands.each do |band| %>
      <tr>
				<td><%= link_to image_tag(band.photo.url(:thumb)), band_path(band) %></td>
        <td><%= link_to band.title, band_path(band) %></td>
        <td><%= band.description %></td>
        <td><%= band.genre %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_band_path(band), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      band_path(band),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bands/new.html.erb
<%- model_class = Band -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bands/show.html.erb
<%- model_class = Band -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:photo) %>:</strong></dt>
  <dd><%= image_tag(@band.photo.url(:medium)) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @band.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @band.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:genre) %>:</strong></dt>
  <dd><%= @band.genre %></dd>
  <dt><strong>Songs:</strong></dt>
  <dd><% Song.find_all_by_band_id(@band.id).each do |song| %>
    <%= link_to( song.title, song_path(song)) %>
		<% end %>
	</dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              bands_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_band_path(@band), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              band_path(@band),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/gigs/_form.html.erb
<%= simple_form_for(@gig, :html => { :class => 'form-horizontal' }) do |f| %>
	<%=	f.input :title %>
	<%=	f.input :description %>
	<%=	f.input :start_time %>
	<%=	f.association :venue %>
	<%=	f.association :bands %>
	<%= f.button :submit %>
<% end %>

app/views/gigs/edit.html.erb
<%- model_class = Gig -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/gigs/index.html.erb
	<div id="masonry-container" class="transitions-enabled infinite-scroll clearfix">
<% @gigs.each do |gig| %>

  <div class="box col5 brow">

  <div class="item">
    <h3><%= link_to(gig.title, gig_path(gig)) %></h3>
  </div>

  <div class="item w1">
    <p>
      <a href="https://scontent-a-ord.xx.fbcdn.net/hphotos-prn1/1234901_10151780690694526_847752889_n.jpg" title="Whitlow's on Wilson by nemoorange, on Flickr"><img src="https://scontent-a-ord.xx.fbcdn.net/hphotos-prn1/1234901_10151780690694526_847752889_n.jpg" alt="Whitlow's on Wilson" /></a>
    </p>
  </div>
	<p>Location:</p><h4><%= link_to(gig.venue.title,venue_path(gig.venue)) %></h4>
  <p><%= gig.description %></p>
	<h4>Band List:</h4>
	<% gig.bands.each do |b| %>
		<div class="item w5 brow">
			<div class="box col1 bandname">
				<%= link_to(b.title,band_path(b)) %>
			</div>
			<div class="box col2">
				<p><%= b.description %></p>
			</div>
			<div class="box col1 songlist">
				<p> Check out their songs!</p>
				<% b.songs.find(:all, limit: 3).each do |s| %>
					<p><%= link_to(s.title, song_path(s)) %></p>
				<% end %>
			</div>
		</div>
	<% end %>

</div>
<% end %>
</div>

<%- model_class = Gig -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:start_time) %></th>
      <th><%= model_class.human_attribute_name(:bands) %></th>
      <th><%= model_class.human_attribute_name(:venue) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @gigs.each do |gig| %>
      <tr>
        <td><%= link_to gig.id, gig_path(gig) %></td>
        <td><%= gig.title %></td>
        <td><%= gig.description %></td>
        <td><%= gig.start_time %></td>
        <td><%= gig.bands.map{|g| g.title}.join(",") %></td>
        <td><%= gig.venue.title %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_gig_path(gig), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      gig_path(gig),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_gig_path,
            :class => 'btn btn-primary' %>

app/views/gigs/new.html.erb
<%- model_class = Gig -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/gigs/show.html.erb
<%- model_class = Gig -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @gig.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @gig.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_time) %>:</strong></dt>
  <dd><%= @gig.start_time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bands) %>:</strong></dt>
  <dd><%= @gig.bands.map{ |b| b.title}.join(", ").html_safe %></dd>
  <dt><strong><%= model_class.human_attribute_name(:venue) %>:</strong></dt>
  <dd><%= @gig.venue.title %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              gigs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_gig_path(@gig), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              gig_path(@gig),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "4play.io" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">4play.io</a>
					<ul class="nav">
						<li class="active"><a href="/venues">Venues</a></li>
						<li><a href="/bands">Bands</a></li>
						<li><a href="/songs">Songs</a></li>
						<li><a href="/gigs">Gigs</a></li>
					</ul>
					<p>derp</p>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Useless Box Thing</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Me 2013</p>
<embed src='http://www.shoutcast.com/media/popupPlayer_V19.swf?stationid=http://yp.shoutcast.com/sbin/tunein-station.pls?id=93412&play_status=1' quality='high' bgcolor='#ffffff' width='398' height='104' name='popupPlayer_V19' align='middle' allowScriptAccess='always' allowFullScreen='true' type='application/x-shockwave-flash' pluginspage='http://www.adobe.com/go/getflashplayer' ></embed>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/songs/_form.html.erb
<%= simple_form_for @song do|f| %>
	<%= f.input :title %>
	<%= f.input :band_id, collection: Band.all %>
	<%= f.input :genre %>
	<%= f.input :mp3 %>
	<%= f.button :submit %>
<% end %>

app/views/songs/edit.html.erb
<%- model_class = Song -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/songs/index.html.erb
<%- model_class = Song -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:band) %></th>
      <th><%= model_class.human_attribute_name(:genre) %></th>
      <th><%= model_class.human_attribute_name(:mp3_file_name) %></th>
      <th><%= model_class.human_attribute_name(:mp3_content_type) %></th>
      <th><%= model_class.human_attribute_name(:mp3_file_size) %></th>
      <th><%= model_class.human_attribute_name(:mp3_updated_at) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= link_to song.id, song_path(song) %></td>
        <td><%= song.title %></td>
        <td><%= song.band %></td>
        <td><%= song.genre %></td>
        <td><%= song.mp3_file_name %></td>
        <td><%= song.mp3_content_type %></td>
        <td><%= song.mp3_file_size %></td>
        <td><%= song.mp3_updated_at %></td>
        <td><%=l song.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_song_path(song), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      song_path(song),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_song_path,
            :class => 'btn btn-primary' %>

app/views/songs/new.html.erb
<%- model_class = Song -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/songs/show.html.erb
<%- model_class = Song -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<p>
<%= audio_tag(@song.mp3.url, autoplay: true, controls: true, autobuffer: true) %>
</p>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @song.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:band) %>:</strong></dt>
  <dd><%= @song.band.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:genre) %>:</strong></dt>
  <dd><%= @song.genre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mp3_file_name) %>:</strong></dt>
  <dd><%= @song.mp3_file_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mp3_content_type) %>:</strong></dt>
  <dd><%= @song.mp3_content_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mp3_file_size) %>:</strong></dt>
  <dd><%= @song.mp3_file_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mp3_updated_at) %>:</strong></dt>
  <dd><%= @song.mp3_updated_at %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              songs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_song_path(@song), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              song_path(@song),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/venues/_form.html.erb
<%= form_for @venue do |f|  %>
  <% if @venue.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@venue.errors.count, "error") %> prohibited
      this venue from being saved:</h2>
    <ul>
    <% @venue.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>

	<p>
		<%= f.label :photo %> 
		<%= f.file_field :photo %> 
	</p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/venues/edit.html.erb
<h1>Editing venue</h1>
 
<%= render 'form' %> 
<%= link_to 'Back', venues_path %>

app/views/venues/index.html.erb
<h1>Listing venues</h1>
<%= link_to 'New venue', new_venue_path %>
<table>
  <tr>
		<th></th>
		<th>Title</th>
    <th>Text</th>
  </tr>

  <% @venues.each do |venue| %>
    <tr>
      <td><%= image_tag venue.photo.url(:thumb) %></td>
      <td><%= venue.title %></td>
      <td><%= venue.text %></td>
			<td><%= link_to 'Show', venue_path(venue) %></td>
			<td><%= link_to 'Edit', edit_venue_path(venue) %></td>
			<td><%= link_to 'Destroy', venue_path(venue), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/venues/new.html.erb
<h1>New Venue</h1>
<%= render 'form' %>
<%= link_to 'Back', venues_path %>

app/views/venues/show.html.erb
<%= image_tag @venue.photo.url %>
<p>
  <strong>Title:</strong>
  <%= @venue.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @venue.text %>
</p>

<%= link_to 'Back', venues_path %>
| <%= link_to 'Edit', edit_venue_path(@venue) %>